services:
  chat:
    command: bun run dev
    volumes:
      - ../../services/chat/src:/app/src

  web:
    command: bun run dev
    volumes:
      - ../../clients/web:/app
      - /app/node_modules
      - /app/.next
