FROM oven/bun:1-alpine AS base

WORKDIR /app
COPY package.json ./
COPY bun.lockb ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

FROM base AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=base /app/.next/standalone ./
COPY --from=base /app/.next/static ./
COPY --from=base /app/public ./public
EXPOSE 3000
CMD ["node", "server.js"]
